import { describe, expect, it } from "vitest";
import { generateCss } from "./generate";
import { BASE_TOKEN_NAMES, THEME_TOKEN_NAMES } from "./types";

describe("generateCss", () => {
  const css = generateCss();
  const prefixed = generateCss("kaipu-");

  it("starts with the GENERATED header comment", () => {
    expect(css.startsWith("/*\n * GENERATED by @kaipu/tokens")).toBe(true);
  });

  it("emits every token under :root with the dark values", () => {
    expect(css).toContain(":root {");
    expect(css).toContain("  --bg-app: #0f0f11;");
    expect(css).toContain("  --accent-primary: #f6055c;");
    expect(css).toContain("  --space-md: 12px;");
    const declarations = css.match(/^ {2}--[a-z0-9-]+:/gm) ?? [];
    // :root declares theme + base once; the light block re-declares theme tokens.
    expect(declarations.length).toBe(THEME_TOKEN_NAMES.length * 2 + BASE_TOKEN_NAMES.length);
  });

  it("emits the light theme as a [data-theme='light'] override of theme tokens only", () => {
    const lightBlock = css.slice(css.indexOf('[data-theme="light"]'));
    expect(lightBlock).toContain("  --bg-app:");
    expect(lightBlock).not.toContain("  --space-md:");
  });

  it("prefixes every custom property when a prefix is given", () => {
    expect(prefixed).toContain("  --kaipu-bg-app: #0f0f11;");
    expect(prefixed).toContain("  --kaipu-space-md: 12px;");
    expect(prefixed).not.toMatch(/^ {2}--(?!kaipu-)/m);
  });

  it("ends with a trailing newline (POSIX file)", () => {
    expect(css.endsWith("}\n")).toBe(true);
  });
});
