import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { base } from "./base";
import { dark } from "./themes/dark";
import { light } from "./themes/light";
import { BASE_TOKEN_NAMES, THEME_TOKEN_NAMES } from "./types";

const HEADER = `/*
 * GENERATED by @kaipu/tokens — do not edit by hand.
 * Edit src/base.ts or src/themes/*.ts, then run \`bun run generate\` here.
 * Dark is the default in :root; light theme overrides are in a separate block.
 */`;

/**
 * Render the full tokens stylesheet. `prefix` is prepended to every custom
 * property name — the desktop consumes the unprefixed flavor, the web consumes
 * `kaipu-` so it can never shadow web-ui's shadcn variables.
 */
export function generateCss(prefix = ""): string {
  // Over-long declarations wrap onto a continuation line, matching oxfmt's CSS
  // style — the generated files must be oxfmt-stable (lint-staged formats staged
  // css, and a formatter rewrite here would break the drift test).
  const declare = (name: string, value: string) => {
    const line = `  --${prefix}${name}: ${value};`;
    return line.length <= 100 ? line : `  --${prefix}${name}:\n    ${value};`;
  };

  const rootLines = [
    ...THEME_TOKEN_NAMES.map((name) => declare(name, dark[name])),
    ...BASE_TOKEN_NAMES.map((name) => declare(name, base[name])),
  ];
  const lightLines = THEME_TOKEN_NAMES.map((name) => declare(name, light[name]));

  return [
    HEADER,
    "",
    ":root {",
    ...rootLines,
    "}",
    "",
    '[data-theme="light"] {',
    ...lightLines,
    "}",
    "",
  ].join("\n");
}

/**
 * Render the typed StyleX layer: `defineVars` with LITERAL values from the
 * same sources as the css flavors (dark is the default, matching :root), plus
 * a `createTheme` carrying the light overrides — ADR 0008, stage 1. A token
 * typo is a compile error; light/dark in the StyleX world is the exported
 * theme, applied by each surface at its themed root. The css flavors keep
 * being generated for every existing `var()` consumer; they retire when the
 * last one does, not before.
 */
export function generateStylex(): string {
  const camel = (name: string) => name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  // Same oxfmt-stability rule as `declare` in generateCss: the generated file
  // must survive the formatter byte-identical, or the drift test dies.
  // oxfmt picks single quotes when the string contains double quotes; mirror it.
  const quote = (value: string) =>
    value.includes('"') && !value.includes("'") ? `'${value}'` : JSON.stringify(value);
  const line = (name: string, value: string) => {
    const one = `  ${camel(name)}: ${quote(value)},`;
    return one.length <= 100 ? one : `  ${camel(name)}:\n    ${quote(value)},`;
  };
  const defaults = [
    ...THEME_TOKEN_NAMES.map((name) => line(name, dark[name])),
    ...BASE_TOKEN_NAMES.map((name) => line(name, base[name])),
  ];
  const lightLines = THEME_TOKEN_NAMES.map((name) => line(name, light[name]));
  return [
    HEADER.replace(
      "Dark is the default in :root; light theme overrides are in a separate block.",
      "Typed tokens: literal values, dark as the default; `lightTheme` carries the overrides.",
    ),
    "",
    'import * as stylex from "@stylexjs/stylex";',
    "",
    "export const tokens = stylex.defineVars({",
    ...defaults,
    "});",
    "",
    "export const lightTheme = stylex.createTheme(tokens, {",
    ...lightLines,
    "});",
    "",
  ].join("\n");
}

if (import.meta.main) {
  const outDir = fileURLToPath(new URL("../css/", import.meta.url));
  mkdirSync(outDir, { recursive: true });
  writeFileSync(`${outDir}tokens.css`, generateCss());
  writeFileSync(`${outDir}tokens.kaipu.css`, generateCss("kaipu-"));
  const stylexDir = fileURLToPath(new URL("../stylex/", import.meta.url));
  mkdirSync(stylexDir, { recursive: true });
  writeFileSync(`${stylexDir}kaipu.stylex.ts`, generateStylex());
  console.log("Wrote css/tokens.css, css/tokens.kaipu.css and stylex/kaipu.stylex.ts");
}
