import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { base } from "./base";
import { dark } from "./themes/dark";
import { light } from "./themes/light";
import { BASE_TOKEN_NAMES, THEME_TOKEN_NAMES } from "./types";

const HEADER = `/*
 * GENERATED by @kaipu/tokens — do not edit by hand.
 * Edit src/base.ts or src/themes/*.ts, then run \`bun run generate\` here.
 * Dark is the default in :root; light theme overrides are in a separate block.
 */`;

/**
 * Render the full tokens stylesheet. `prefix` is prepended to every custom
 * property name — the desktop consumes the unprefixed flavor, the web consumes
 * `kaipu-` so it can never shadow web-ui's shadcn variables.
 */
export function generateCss(prefix = ""): string {
  // Over-long declarations wrap onto a continuation line, matching oxfmt's CSS
  // style — the generated files must be oxfmt-stable (lint-staged formats staged
  // css, and a formatter rewrite here would break the drift test).
  const declare = (name: string, value: string) => {
    const line = `  --${prefix}${name}: ${value};`;
    return line.length <= 100 ? line : `  --${prefix}${name}:\n    ${value};`;
  };

  const rootLines = [
    ...THEME_TOKEN_NAMES.map((name) => declare(name, dark[name])),
    ...BASE_TOKEN_NAMES.map((name) => declare(name, base[name])),
  ];
  const lightLines = THEME_TOKEN_NAMES.map((name) => declare(name, light[name]));

  return [
    HEADER,
    "",
    ":root {",
    ...rootLines,
    "}",
    "",
    '[data-theme="light"] {',
    ...lightLines,
    "}",
    "",
  ].join("\n");
}

/**
 * Render the typed StyleX layer: `defineVars` whose VALUES are references to
 * the prefixed custom properties the css flavors above declare. This gives
 * components typed, rename-safe token access (a typo is a compile error)
 * while the existing `[data-theme]` blocks keep owning the actual values —
 * no theming mechanism changes hands. Replacing the references with literal
 * values + `createTheme` (retiring the css imports entirely) is the design
 * decision the shared-styling spec owns; this file deliberately does not
 * make it.
 */
export function generateStylex(): string {
  const camel = (name: string) => name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  const entries = [...THEME_TOKEN_NAMES, ...BASE_TOKEN_NAMES].map(
    (name) => `  ${camel(name)}: "var(--kaipu-${name})",`,
  );
  return [
    HEADER.replace(
      "Dark is the default in :root; light theme overrides are in a separate block.",
      "Typed references over the kaipu-prefixed custom properties in css/.",
    ),
    "",
    'import * as stylex from "@stylexjs/stylex";',
    "",
    "export const tokens = stylex.defineVars({",
    ...entries,
    "});",
    "",
  ].join("\n");
}

if (import.meta.main) {
  const outDir = fileURLToPath(new URL("../css/", import.meta.url));
  mkdirSync(outDir, { recursive: true });
  writeFileSync(`${outDir}tokens.css`, generateCss());
  writeFileSync(`${outDir}tokens.kaipu.css`, generateCss("kaipu-"));
  const stylexDir = fileURLToPath(new URL("../stylex/", import.meta.url));
  mkdirSync(stylexDir, { recursive: true });
  writeFileSync(`${stylexDir}kaipu.stylex.ts`, generateStylex());
  console.log("Wrote css/tokens.css, css/tokens.kaipu.css and stylex/kaipu.stylex.ts");
}
