import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { base } from "./base";
import { dark } from "./themes/dark";
import { light } from "./themes/light";
import { BASE_TOKEN_NAMES, THEME_TOKEN_NAMES } from "./types";

const HEADER = `/*
 * GENERATED by @kaipu/tokens — do not edit by hand.
 * Edit src/base.ts or src/themes/*.ts, then run \`bun run generate\` here.
 * Dark is the default in :root; light theme overrides are in a separate block.
 */`;

/**
 * Render the full tokens stylesheet. `prefix` is prepended to every custom
 * property name — the desktop consumes the unprefixed flavor, the web consumes
 * `kaipu-` so it can never shadow web-ui's shadcn variables.
 */
export function generateCss(prefix = ""): string {
  const declare = (name: string, value: string) => `  --${prefix}${name}: ${value};`;

  const rootLines = [
    ...THEME_TOKEN_NAMES.map((name) => declare(name, dark[name])),
    ...BASE_TOKEN_NAMES.map((name) => declare(name, base[name])),
  ];
  const lightLines = THEME_TOKEN_NAMES.map((name) => declare(name, light[name]));

  return [
    HEADER,
    "",
    ":root {",
    ...rootLines,
    "}",
    "",
    '[data-theme="light"] {',
    ...lightLines,
    "}",
    "",
  ].join("\n");
}

if (import.meta.main) {
  const outDir = fileURLToPath(new URL("../css/", import.meta.url));
  mkdirSync(outDir, { recursive: true });
  writeFileSync(`${outDir}tokens.css`, generateCss());
  writeFileSync(`${outDir}tokens.kaipu.css`, generateCss("kaipu-"));
  console.log("Wrote css/tokens.css and css/tokens.kaipu.css");
}
