import type { QueryClient } from "@tanstack/react-query";

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import {
  HeadContent,
  Outlet,
  Scripts,
  createRootRouteWithContext,
  useRouter,
  useRouterState,
} from "@tanstack/react-router";
import { TanStackRouterDevtools } from "@tanstack/react-router-devtools";

import { I18nProvider, type Locale } from "@kaipu/i18n";

import { siteHeadMeta } from "@/lib/seo";
import appCss from "../index.css?url";
import stylexCss from "../stylex.css?url";
import { forget, readCovering, remember } from "@/lib/i18n/messages-cache";
import type { MessageTree } from "@/lib/i18n/pick-messages";
import { slicesForPath, type MessageSlice } from "@/lib/i18n/route-messages";
import { getLocale } from "@/server-functions/get-locale";
import { setLocale as setLocaleFn } from "@/server-functions/set-locale";
import { getLandingTheme } from "@/server-functions/get-landing-theme";
import { readLandingThemeCookie, type LandingTheme } from "@/lib/landing-theme";

export interface RouterAppContext {
  queryClient: QueryClient;
  locale: Locale;
  /** Only the slices the matched route renders, in the active locale. */
  messages: MessageTree;
  /** Which slices `messages` was filtered to; see `lib/i18n/route-messages`. */
  messageSlices: MessageSlice[];
  /** The landing's own dark/light choice; unrelated to the app shell's theme. */
  landingTheme: LandingTheme;
}

export const Route = createRootRouteWithContext<RouterAppContext>()({
  head: ({ match }) => ({
    meta: siteHeadMeta(match.context.locale),
    links: [
      {
        rel: "stylesheet",
        href: appCss,
      },
      // The atomic CSS of the shared @kaipu/ui components, which the landing's
      // product shot renders. Generated by the PostCSS scanner at `@stylex;`.
      { rel: "stylesheet", href: stylexCss },
      // Raster only: the fox has no vector cut yet (see @kaipu/brand), and a
      // stale SVG here would win over every PNG in Chrome.
      { rel: "icon", href: "/favicon.ico", sizes: "48x48" },
      { rel: "icon", type: "image/png", sizes: "32x32", href: "/favicon-32x32.png" },
      { rel: "icon", type: "image/png", sizes: "16x16", href: "/favicon-16x16.png" },
      { rel: "apple-touch-icon", href: "/apple-touch-icon.png" },
      { rel: "manifest", href: "/site.webmanifest" },
    ],
  }),
  component: RootDocument,
  // No `staleTime` here. A fresh root match skips `beforeLoad` on client-side
  // navigation, and `beforeLoad` is what loads the messages the next route needs:
  // with a staleTime the legal pages rendered against the home's message slices.
  // The round trips it used to save are avoided inside `beforeLoad` itself (the
  // messages cache, and the theme cookie read in the browser).
  // The session is deliberately not resolved here: the public pages do not
  // reflect it, and fetching it would put the auth client on every route. The
  // layouts that need it (`auth`, `_authenticated`) load it themselves.
  // `location` is typed by hand: the registered router type is derived from this
  // very route, so reading it from the inferred context makes TypeScript give up
  // and type the whole callback as returning `never`.
  beforeLoad: async ({ location }: { location: { pathname: string } }) => {
    const slices = slicesForPath(location.pathname);
    // On the client a slice already in hand is not worth a round trip.
    const [i18n, landingTheme] = await Promise.all([
      readCovering(slices) ?? getLocale({ data: { slices } }),
      // The cookie is not httpOnly, so the browser can read it without a call.
      typeof window === "undefined"
        ? getLandingTheme().then((r) => r.theme)
        : readLandingThemeCookie(),
    ]);
    return {
      locale: i18n.locale,
      messages: remember(i18n.locale, slices, i18n.messages),
      messageSlices: slices,
      landingTheme,
    };
  },
});

// Critical inline styles to prevent flash of unstyled content
/*
 * The first paint, before any stylesheet has arrived.
 *
 * It has to agree with the theme the page is about to render, or the visitor
 * watches the wrong one and then a flip. Measured on a throttled connection the
 * stylesheets gate the first paint at ~2.7s, so "briefly" means seconds: a
 * light-theme visitor used to stare at a black screen for most of the load and
 * then have it turn white.
 */
function criticalStyles(light: boolean): string {
  return `
  html, body {
    background-color: ${light ? "#faf8f5" : "oklch(14.5% 0 0)"};
    color: ${light ? "#141416" : "oklch(98.5% 0 0)"};
    margin: 0;
    padding: 0;
  }
`;
}

function RootDocument() {
  const context = Route.useRouteContext();
  const router = useRouter();
  const { locale } = context;
  // The SSR payload is the client's first copy of the messages; keep it so the
  // next client-side navigation only asks for what is missing. No-op on the server.
  remember(locale, context.messageSlices, context.messages);

  // Public pages bring their own header and footer, so the app shell must stand
  // down for them. Read from the route's own staticData rather than matching on
  // the pathname: a new public page then declares its shell next to its route
  // instead of having to be remembered in a list here.
  const isMarketing = useRouterState({
    select: (s) => s.matches.some((m) => m.staticData.shell === "marketing"),
  });

  // Both the <html> class and the pre-stylesheet background hang off this.
  const isLandingLight = isMarketing && context.landingTheme === "light";

  // Persist to the cookie, drop the cache (it holds the old language), then
  // re-run beforeLoad so the tree re-renders with the new messages (resolved
  // server-side). Until they land the provider keeps showing the old text.
  const handleSetLocale = async (next: Locale) => {
    await setLocaleFn({ data: next });
    forget();
    await router.invalidate();
  };

  return (
    <html
      lang={locale}
      // `dark` is the APP's Tailwind theme and stays on for every app route.
      // Only the landing has a light choice, and only the landing may drop it.
      className={isLandingLight ? undefined : "dark"}
      suppressHydrationWarning
    >
      <head>
        <style dangerouslySetInnerHTML={{ __html: criticalStyles(isLandingLight) }} />
        <HeadContent />
      </head>
      <body suppressHydrationWarning>
        <I18nProvider
          initialLocale={locale}
          // Only the active locale's messages are loaded. Both keys point at them so
          // the provider never reads an empty catalog in the moment between the
          // locale state flipping and the reloaded messages arriving.
          messagesByLocale={{ es: context.messages, en: context.messages }}
          onLocaleChange={(next) => void handleSetLocale(next)}
        >
          {/* The app header, footer and toaster live in the `auth` and
              `_authenticated` layouts (`AppShell`), so the public pages never
              download them. */}
          <div className="min-h-svh">
            {isMarketing ? (
              <main>
                <Outlet />
              </main>
            ) : (
              <Outlet />
            )}
          </div>
        </I18nProvider>
        <TanStackRouterDevtools position="bottom-left" />
        <ReactQueryDevtools position="bottom" buttonPosition="bottom-right" />
        <Scripts />
      </body>
    </html>
  );
}
