// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import mermaid from "astro-mermaid";

// https://astro.build/config
export default defineConfig({
  integrations: [
    mermaid(),
    starlight({
      title: "Kaipu",
      lastUpdated: true,
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/withastro/starlight",
        },
      ],
      sidebar: [
        {
          label: "Getting Started",
          items: [{ slug: "index" }, { slug: "commands" }],
        },
        {
          label: "Briefings",
          autogenerate: { directory: "briefings" },
        },
        {
          label: "Marketing",
          autogenerate: { directory: "marketing" },
        },
        {
          label: "Stack",
          items: [{ slug: "stack/hono" }, { slug: "stack/better-auth-electron-bug" }],
        },
        {
          label: "Desktop App",
          items: [
            { slug: "desktop/product-philosophy" },
            { slug: "desktop/filesystem-first-monetization" },
            { slug: "desktop/recording-pipeline" },
            { slug: "desktop/renderer-architecture" },
            { slug: "desktop/main-process-architecture" },
            { slug: "desktop/ipc-contract" },
            { slug: "desktop/library-vault" },
            { slug: "desktop/permissions-and-onboarding" },
            { slug: "desktop/electron-vs-tauri" },
          ],
        },
        {
          label: "Features",
          autogenerate: { directory: "features" },
        },
        {
          label: "Specs",
          autogenerate: { directory: "specs" },
        },
        {
          label: "Plans",
          autogenerate: { directory: "plans" },
        },
        {
          label: "Backlog",
          items: [
            "backlog/deploy-environments",
            { slug: "backlog" },
            { slug: "backlog/code-quality-audit" },
            { slug: "backlog/lefthook-migration" },
            { slug: "backlog/ci-local-first-verification" },
            { slug: "backlog/desktop-auth-pages" },
            { slug: "backlog/fable-audit" },
            { slug: "backlog/fable-audit-results" },
            { slug: "backlog/aspect-ratio-distortion" },
            { slug: "backlog/editor-zoom" },
            { slug: "backlog/recording-compositor-perf" },
            { slug: "backlog/roadmap" },
            { slug: "backlog/product-growth" },
            { slug: "backlog/free-tier-no-watermark" },
            { slug: "backlog/windows-beta" },
            { slug: "backlog/open-source-security-sweep" },
            { slug: "backlog/video-editor-v2-handoff" },
            { slug: "backlog/live-recording-controls" },
            { slug: "backlog/settings-updates" },
            { slug: "backlog/settings-screenshots" },
            { slug: "backlog/settings-screenshot-clipboard" },
            { slug: "backlog/video-editor-mute" },
            { slug: "backlog/editor-space-and-window-presets" },
            { slug: "backlog/capture-panel-latency" },
            { slug: "backlog/editor-title-input" },
            { slug: "backlog/library-lineage" },
            { slug: "backlog/ci-minutes-audit" },
            { slug: "backlog/ci-cost-handoff" },
            { slug: "backlog/watermark-redesign" },
            { slug: "backlog/bug-control-bar-hides-last-terminal-line" },
            { slug: "backlog/dock-and-app-switcher" },
            { slug: "backlog/standalone-editor" },
            { slug: "backlog/version-gate" },
            { slug: "backlog/auto-update" },
            { slug: "backlog/shared-tokens-package" },
            { slug: "backlog/stylex-migration" },
            { slug: "backlog/r2-storage-architecture" },
            { slug: "backlog/cloud-recordings-upload" },
            { slug: "backlog/optional-cloud" },
            { slug: "backlog/optional-cloud-handoff" },
            { slug: "backlog/desktop-cloud-sync-gap" },
            { slug: "backlog/cloud-error-states" },
            { slug: "backlog/legal-documents" },
            { slug: "backlog/public-roadmap-page" },
            { slug: "backlog/public-page-shell" },
            { slug: "backlog/plans-and-entitlements" },
            { slug: "backlog/backend-security-hardening" },
            { slug: "backlog/dependency-security-upgrades" },
            { slug: "backlog/r2-upload-integrity" },
            { slug: "backlog/production-cloud-security" },
            { slug: "backlog/desktop-auth-and-r2-cors" },
            { slug: "backlog/api-abuse-controls" },
            { slug: "backlog/electron-security-hardening" },
            { slug: "backlog/cloud-data-lifecycle" },
            { slug: "backlog/playwright-e2e" },
            { slug: "backlog/i18n" },
            { slug: "backlog/settings-roadmap" },
            { slug: "backlog/shortcuts" },
            { slug: "backlog/screenshots" },
            { slug: "backlog/editor-toolbar-responsive" },
            { slug: "backlog/video-editor-annotation-inspector" },
            { slug: "backlog/screenshot-save-strategy" },
            { slug: "backlog/screenshot-scene-doc" },
            { slug: "backlog/screenshot-redaction" },
            { slug: "backlog/screenshot-crop" },
            { slug: "backlog/screenshot-freehand" },
            { slug: "backlog/screenshot-auto-select" },
            { slug: "backlog/widget-capture-tabs" },
            { slug: "backlog/screen-picker-thumbnail-perf" },
            { slug: "backlog/export-formats" },
            { slug: "backlog/video-editor" },
            { slug: "backlog/video-editor-camera-box-ux" },
            { slug: "backlog/video-editor-zoom-blur-cover" },
            { slug: "backlog/cursor-sprite-capture" },
            { slug: "backlog/edit-state-indicators" },
            { slug: "backlog/library-lineage" },
          ],
        },
        {
          label: "Architecture",
          autogenerate: { directory: "architecture" },
        },
        {
          label: "Deployment",
          autogenerate: { directory: "deployment" },
        },
        {
          label: "Testing",
          autogenerate: { directory: "testing" },
        },
        {
          label: "Authentication",
          items: [
            { slug: "authentication" },
            { slug: "authentication/overview" },
            { slug: "authentication/implementation" },
            { slug: "authentication/quick-reference" },
          ],
        },
        {
          label: "Backend",
          autogenerate: { directory: "backend" },
        },
        {
          label: "Frontend",
          autogenerate: { directory: "frontend" },
        },
        {
          label: "Changelog",
          items: [{ slug: "changelog" }],
        },
      ],
    }),
  ],
});
