/*
 * GENERATED by @kaipu/tokens — do not edit by hand.
 * Edit src/base.ts or src/themes/*.ts, then run `bun run generate` here.
 * Typed references over the kaipu-prefixed custom properties in css/.
 */

import * as stylex from "@stylexjs/stylex";

export const tokens = stylex.defineVars({
  bgApp: "var(--kaipu-bg-app)",
  bgSidebar: "var(--kaipu-bg-sidebar)",
  bgCard: "var(--kaipu-bg-card)",
  bgCardHover: "var(--kaipu-bg-card-hover)",
  bgInput: "var(--kaipu-bg-input)",
  bgModal: "var(--kaipu-bg-modal)",
  bgOverlay: "var(--kaipu-bg-overlay)",
  border: "var(--kaipu-border)",
  borderLight: "var(--kaipu-border-light)",
  textPrimary: "var(--kaipu-text-primary)",
  textSecondary: "var(--kaipu-text-secondary)",
  textMuted: "var(--kaipu-text-muted)",
  accentPrimary: "var(--kaipu-accent-primary)",
  accentPrimaryHover: "var(--kaipu-accent-primary-hover)",
  glowAccent: "var(--kaipu-glow-accent)",
  accentGreen: "var(--kaipu-accent-green)",
  accentRed: "var(--kaipu-accent-red)",
  accentRedHover: "var(--kaipu-accent-red-hover)",
  accentYellow: "var(--kaipu-accent-yellow)",
  accentPurple: "var(--kaipu-accent-purple)",
  spaceXs: "var(--kaipu-space-xs)",
  spaceSm: "var(--kaipu-space-sm)",
  spaceMd: "var(--kaipu-space-md)",
  spaceLg: "var(--kaipu-space-lg)",
  spaceXl: "var(--kaipu-space-xl)",
  space2xl: "var(--kaipu-space-2xl)",
  radiusSm: "var(--kaipu-radius-sm)",
  radiusMd: "var(--kaipu-radius-md)",
  radiusLg: "var(--kaipu-radius-lg)",
  fontFamily: "var(--kaipu-font-family)",
  fontMono: "var(--kaipu-font-mono)",
  fontSizeXs: "var(--kaipu-font-size-xs)",
  fontSizeSm: "var(--kaipu-font-size-sm)",
  fontSizeBase: "var(--kaipu-font-size-base)",
  fontSizeMd: "var(--kaipu-font-size-md)",
  fontSizeLg: "var(--kaipu-font-size-lg)",
  fontSizeXl: "var(--kaipu-font-size-xl)",
  fontWeightNormal: "var(--kaipu-font-weight-normal)",
  fontWeightMedium: "var(--kaipu-font-weight-medium)",
  fontWeightSemibold: "var(--kaipu-font-weight-semibold)",
  sidebarWidth: "var(--kaipu-sidebar-width)",
  titlebarHeight: "var(--kaipu-titlebar-height)",
  transition: "var(--kaipu-transition)",
  transitionSlow: "var(--kaipu-transition-slow)",
});
