import { defineConfig } from "tsdown";

// Build the TS exports to `dist/` (used by `publishConfig`); `devExports: true`
// keeps the local monorepo `exports` pointed at source (same pattern as
// @kaipu/i18n). The CSS files are static exports generated by `bun run generate`
// and committed — tsdown never touches them, so re-add their subpaths.
export default defineConfig({
  entry: ["src/index.ts"],
  format: "esm",
  dts: true,
  clean: true,

  exports: {
    devExports: true,
    customExports(exports) {
      exports["./css"] = "./css/tokens.css";
      exports["./css/kaipu"] = "./css/tokens.kaipu.css";
      return exports;
    },
  },
});
