import { defineConfig } from "tsdown";

// Build the TS exports to `dist/` (used by `publishConfig`); `devExports: true`
// keeps the local monorepo `exports` pointed at source (same pattern as
// @kaipu/i18n). The CSS files are static exports generated by `bun run generate`
// and committed — tsdown never touches them, so re-add their subpaths.
export default defineConfig({
  entry: ["src/index.ts"],
  format: "esm",
  dts: true,
  clean: true,

  exports: {
    devExports: true,
    customExports(exports) {
      exports["./css"] = "./css/tokens.css";
      exports["./css/kaipu"] = "./css/tokens.kaipu.css";
      // Typed StyleX references, generated by `bun run generate` like the css
      // flavors. Source-exported on purpose: the consuming app compiles the
      // defineVars call. The subpath must end in `.stylex` — the StyleX
      // compiler refuses to resolve variable imports from any other spelling.
      exports["./kaipu.stylex"] = "./stylex/kaipu.stylex.ts";
      return exports;
    },
  },
});
